### ISSUE TITLE
Sign in with Auth0 button is not visible

### ISSUE THREAD

**Issue by sepTN** [NodeBB-Community/nodebb-plugin-sso-auth0#9]
I've installed the plugin and setup my Auth0. However on my login page the button is like this 

![image](https://github.com/NodeBB-Community/nodebb-plugin-sso-auth0/assets/13846022/ba863b99-3b06-4d0c-9172-fcbebfc90bde)

However if I click it, and perform SSO with that, it does seems to work. So it's a visual bug

`nodebb-plugin-sso-auth0
NodeBB Auth0 SSO

Installed 4.1.1 | Latest 4.1.1`

**Comment by barisusakli** [comment]
@sepTN thanks for reporting
![image](https://github.com/NodeBB-Community/nodebb-plugin-sso-auth0/assets/2583394/b6b6e5ae-0145-4163-9a29-f11fb45d8c14)

**Comment by barisusakli** [comment]
published 4.1.3
